version: "3"
services:
  default:
    container_name: soundoftext-api
    depends_on:
      - mongo
    env_file: soundoftext-api.env
    image: ncpierson/soundoftext-api:latest
    ports:
      - "5757:5757"
    restart: always
  mongo:
    container_name: soundoftext-db
    image: mongo
    restart: always
