version: "3"
services:
  default:
    command: pm2-dev start pm2.json
    container_name: soundoftext-api
    depends_on:
      - mongo
    environment:
      - DB__HOST
      - STORAGE__ACCESS_KEY_ID
      - STORAGE__SECRET_ACCESS_KEY
      - STRIPE__KEY
    image: ncpierson/soundoftext-api:latest
    ports:
      - "5757:5757"
    restart: always
    volumes:
      - "./src:/usr/src/app/src"
  mongo:
    container_name: soundoftext-db
    image: mongo
    restart: always
