debug = false

logLevel = "INFO"
defaultEntryPoints = ["https", "http"]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[retry]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[acme]
acmeLogging = true
email = "me@nick.exposed"
entryPoint = "https"
onHostRule = true
storage = "acme.json"
  [acme.httpChallenge]
  entryPoint = "http"
  [[acme.domains]]
  main = "soundoftext.com"
  sans = ["api.soundoftext.com"]
