debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[retry]

[entryPoints]
  [entryPoints.http]
  address = ":80"
